# Generated by Django 2.1.1 on 2018-09-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='password',
        ),
    ]
