# Generated by Django 2.1.1 on 2018-09-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mark',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
