# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_auto_20180921_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('mobno', models.BigIntegerField(default=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
